-- 코드를 입력하세요
-- SELECT * FROM USED_GOODS_BOARD;
-- 게시글 제목, 게시글 ID, 댓글 ID, 
-- 댓글 작성자 ID, 댓글 내용, 댓글 작성일
-- BOARD : BOARD_ID, TITLE
-- REPLY : BOARD_ID, REPLY_ID, WRITER_ID, CONTENTS, CREATED_DATE
-- SELECT * FROM USED_GOODS_REPLY
-- WHERE CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
-- UNION
SELECT * FROM USED_GOODS_BOARD
WHERE CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'